# Generated by Django 4.0 on 2021-12-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('codice_fiscale', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=25)),
                ('cognome', models.CharField(max_length=25)),
                ('data_nascita', models.DateField()),
                ('via', models.CharField(max_length=30)),
                ('cap', models.CharField(max_length=5)),
                ('citta', models.CharField(max_length=25)),
                ('provincia', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('data_iscrizione', models.DateField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssicurazioneMedica.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Amministratore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=100)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssicurazioneMedica.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
