# Generated by Django 4.0 on 2021-12-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssicurazioneMedica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amministratore',
            name='username',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
