# Generated by Django 4.0 on 2021-12-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssicurazioneMedica', '0002_alter_amministratore_username_alter_cliente_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amministratore',
            old_name='username',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='username',
            new_name='email',
        ),
    ]
