# Generated by Django 4.0 on 2021-12-14 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssicurazioneMedica', '0003_rename_username_amministratore_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amministratore',
            name='session_valid_until',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='amministratore',
            name='token',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AddField(
            model_name='cliente',
            name='session_valid_until',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cliente',
            name='token',
            field=models.CharField(default='', max_length=22),
        ),
    ]
