# Generated by Django 4.0 on 2021-12-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssicurazioneMedica', '0005_alter_amministratore_email_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiesteSottoscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('evasa', models.BinaryField(default=False)),
                ('prezzoProposto', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssicurazioneMedica.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DatiMedici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesso', models.CharField(max_length=1)),
                ('peso', models.FloatField()),
                ('altezza', models.FloatField()),
                ('numero_figli', models.IntegerField()),
                ('fumatore', models.BinaryField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssicurazioneMedica.cliente')),
            ],
        ),
    ]
