# Generated by Django 4.0 on 2021-12-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssicurazioneMedica', '0006_richiestesottoscrizione_datimedici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datimedici',
            name='fumatore',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='richiestesottoscrizione',
            name='evasa',
            field=models.BooleanField(default=False),
        ),
    ]
