# Generated by Django 4.0 on 2021-12-18 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssicurazioneMedica', '0008_polizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeseMediche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_spesa', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('importo', models.FloatField()),
                ('polizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssicurazioneMedica.polizza')),
            ],
        ),
    ]
