# Generated by Django 4.0 on 2021-12-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssicurazioneMedica', '0010_spesemedichecliente_delete_spesemediche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spesemedichecliente',
            name='data',
            field=models.DateField(),
        ),
    ]
