# Generated by Django 4.0 on 2021-12-31 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssicurazioneMedica', '0011_alter_spesemedichecliente_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='richiestesottoscrizione',
            name='cliente',
        ),
        migrations.AddField(
            model_name='richiestesottoscrizione',
            name='dati_medici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssicurazioneMedica.datimedici'),
            preserve_default=False,
        ),
    ]
